const SIB_TEMPLATES = {
  INIT: 0,
  LOGIN: 0,
  WELCOME_EMAIL: 0,
  SEND_VERIFICATION_CODE: 0,
  ACTIVATE_ADMIN_ACCOUNT: 0,
  SUCCESSFUL_PROFILE_UPDATE: 0,
  VERIFY_EMAIL: 0,
  TWO_FACTOR_TOGGLED: 0,
};
export default SIB_TEMPLATES;
